In [75]:
import numpy as np


class SVM:
    def __init__(self, lr=0.001, lambda_parameter=0.01, n_iters=1000):
        self.lr = lr
        self.lambda_parameter = lambda_parameter
        self.n_iters = n_iters
        self.w = None
        self.b = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # Basic conversion, stored in diff y
        y_ = np.where(y <= 0, -1, 1)

        # initalizing the weights and bias with zeros
        self.w = np.zeros(n_features)
        self.b = 0

        # Gradient descenting for investigating through obs to find apt wt and b that can give high accuracy and low error
        for _ in range(self.n_iters):
           
            for idx, x_i in enumerate(X):
                
           
                condition = y[idx] * (np.dot(x_i, self.w) - self.b) >= 1

                if condition:
                    self.w -= self.lr * (2 * self.lambda_parameter * self.w)
                else:
                    self.w -= self.lr * (2 * self.lambda_parameter * self.w -np.dot(x_i, y_[idx]))
                    self.b -= self.lr * y_[idx]

    def predict(self, X):
        # w * x - b
        linear_model = np.dot(X, self.w) - self.b
        return np.sign(linear_model)

In [76]:
import pandas as pd

url="https://raw.githubusercontent.com/nsethi31/Kaggle-Data-Credit-Card-Fraud-Detection/master/creditcard.csv"
df=pd.read_csv(url)



In [50]:
df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [51]:
df["Class"].unique()

array([0, 1])

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811730e-02, ...,
        -2.10530530e-02,  1.49620000e+02,  0.00000000e+00],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
         1.47241690e-02,  2.69000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.97518410e-02,  3.78660000e+02,  0.00000000e+00],
       ...,
       [ 1.72788000e+05,  1.91956501e+00, -3.01253846e-01, ...,
        -2.65608290e-02,  6.78800000e+01,  0.00000000e+00],
       [ 1.72788000e+05, -2.40440050e-01,  5.30482513e-01, ...,
         1.04532821e-01,  1.00000000e+01,  0.00000000e+00],
       [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
         1.36489140e-02,  2.17000000e+02,  0.00000000e+00]])

In [77]:

from sklearn.model_selection import train_test_split


X = df.drop("Class", axis=1)
y = df["Class"]
y=np.where(y==0,-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [78]:
X_train=X_train.to_numpy()


In [79]:
clf=SVM()

In [59]:
X_train


array([[ 1.30124000e+05,  1.78872868e+00, -3.47367140e-02, ...,
         2.25781280e-02, -2.52501050e-02,  4.00600000e+01],
       [ 1.27425000e+05, -7.54001302e-01, -5.20248290e-01, ...,
         3.46141944e-01,  1.03962406e-01,  1.52650000e+02],
       [ 1.19569000e+05,  2.27402054e+00, -1.58205484e+00, ...,
         1.04802910e-02, -6.39950350e-02,  6.00000000e+00],
       ...,
       [ 1.46790000e+05, -7.69071570e-02, -7.88713586e-01, ...,
         1.92628710e-02, -5.27517390e-02,  1.78900000e+01],
       [ 3.07970000e+04, -5.04665151e-01,  1.30198928e+00, ...,
         2.21468765e-01,  1.97456568e-01,  7.90000000e-01],
       [ 6.21280000e+04,  1.08518019e+00, -3.08109449e-01, ...,
         2.31532660e-02,  4.02627520e-02,  9.70600000e+01]])

In [80]:
clf.fit(X_train,y_train)

In [ ]:
X_test=X_test.to_numpy()

In [86]:
y_pred=clf.predict(X_test)

In [84]:
clf.w

array([-8.00778039e+00, -4.28993792e-01,  3.37405103e-01, -6.21360101e-01,
        3.98609827e-01, -2.63348122e-01, -1.11998929e-01, -5.15905781e-01,
       -1.71234274e-02, -2.28872206e-01, -4.97079863e-01,  3.28310302e-01,
       -5.35927553e-01, -9.33276970e-03, -5.92722990e-01, -6.30778447e-03,
       -3.48345245e-01, -5.61223391e-01, -1.82913487e-01,  6.45298619e-02,
        4.07806774e-02,  5.50220270e-02,  5.39969899e-03,  1.47199739e-02,
       -6.25860629e-03,  9.74231194e-03,  9.07110569e-03,  6.69634265e-03,
        7.90656346e-03,  9.49519861e-01])

In [85]:
clf.b

-53.284999999966516

In [87]:
y_pred

array([-1., -1., -1., ..., -1., -1., -1.])

In [88]:

from sklearn import metrics


print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.99830060953344


AN ACCURACY OF 99%